### ISSUE TITLE
error parsing JSON config file

### ISSUE THREAD

**Issue by LJHG** [acheong08/vectordb#3]
Hi, I'm trying to run 
```go
func TestAdd(t *testing.T) {
	client, err := vectordb.NewClient("test_db.gob")
	if err != nil {
		t.Errorf("Error creating new client: %v", err)
	}

	err = client.Add("Hello World")
	if err != nil {
		t.Errorf("Error adding document to client: %v", err)
	}
}
```
and got this
`{"level":"fatal","error":"error parsing JSON config file \"/Users/lm/.models/sentence-transformers/all-MiniLM-L6-v2/config.json\": EOF","time":"2023-07-15T15:53:40+08:00"}`

I take a look into the json file and found out it to be empty.

Any thoughts on this issue?🤔

**Comment by acheong08** [comment]
something went wrong on download. You can fetch manually through https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/tree/main

**Comment by LJHG** [comment]
wroks for me, thanks!
